//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace CustomBuiltPCs
{
    /// <summary>
    /// Make a new Business class computer
    /// </summary>
    public class BusinessMachineMaker : IMachineMaker
    {
        public virtual CPU makeCPU()
        {
            return new CPUMidRange();
        }

        public virtual RAM makeRAM()
        {
            return new BusinessRAM();
        }

        public virtual GFX makeGFX()
        {
            return new GFXLowEnd();
        }

    }
}

