//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Component
{
	protected virtual int Price
	{
		get;
		set;
	}

	protected virtual string Description
	{
		get;
		set;
	}

	public static string toString()
	{
		throw new System.NotImplementedException();
	}

}

