//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Component
{
	public virtual double Price
	{
		get;
		set;
	}

	public virtual string Description
	{
		get;
		set;
	}

	public string ToString()
	{
        return "$" + Price + "\t" + Description;
	}
}