//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace CustomBuiltPCs { 
public class BusinessRAM :  RAM
{
	public BusinessRAM()
	{
        this.Description = "1000Mhz 4GB Generic";
        this.Price = 200;
	}

}

}