//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace CustomBuiltPCs
{
    public class GFXLowEnd : GFX
    {
        public GFXLowEnd()
        {
            this.Description = "Intel 4000 HD";
            this.Price = 150;
        }

    }

}