//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace CustomBuiltPCs {
    public class CPUHighEnd : CPU
    {
        public CPUHighEnd()
        {
            this.Description = "Intel Core i7 4.0 Ghz";
            this.Price = 500;
        }
    }
}

