//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace CustomBuiltPCs
{
    public class GameRAM : RAM
    {
        public GameRAM()
        {
            this.Description = "2666MHz 8GB Kingston";
            this.Price = 800;
        }

    }

}