//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace CustomBuiltPCs
{
    /// <summary>
    /// Make a new Business class computer
    /// </summary>
    public class BusinessMachineMaker : IMachineMaker
    {
        public virtual CPU makeCPU()
        {
            return new CPUMidRange();
        }

        public virtual RAM makeRAM()
        {
            return new BusinessRAM();
        }

        public virtual GFX makeGFX()
        {
            return new GFXLowEnd();
        }

        public virtual Monitor makeMonitor()
        {
            Monitor theMonitor;
            //Choose a monitor from the current options randomly
            Random rnd = new Random();
            int choose = rnd.Next(1, 3);
            switch (choose)
            {
                case 1:
                    theMonitor = new OfficeMonitor();
                    break;
                case 2:
                default:
                    theMonitor = new RecycledMonitor();
                    break;
            }
            return theMonitor;
        }
    }
}

